# Generated by Django 3.1.2 on 2021-08-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram2', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
