# Generated by Django 3.1.2 on 2021-08-08 05:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram2', '0006_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='chatList',
            field=models.ManyToManyField(blank=True, related_name='chatList', to=settings.AUTH_USER_MODEL),
        ),
    ]
