# Generated by Django 3.1.2 on 2021-08-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram2', '0007_follow_chatlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
