# Generated by Django 3.1.2 on 2021-08-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram2', '0008_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
