# Generated by Django 3.1.2 on 2021-08-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram2', '0010_auto_20210809_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profilePicture',
            field=models.ImageField(default='images/useravater.png', upload_to='images/profile/'),
        ),
    ]
