# Generated by Django 3.1.2 on 2021-08-12 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram2', '0011_auto_20210809_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='webste',
            new_name='website',
        ),
    ]
