# Generated by Django 3.1.2 on 2021-08-12 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram2', '0012_auto_20210812_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to=settings.AUTH_USER_MODEL),
        ),
    ]
