# Generated by Django 3.1.2 on 2021-08-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram2', '0015_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='instagram2.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.CharField(choices=[('comment', 'commented'), ('like', 'liked'), ('follow', 'following')], default='like', max_length=20),
        ),
    ]
