# Generated by Django 3.1.2 on 2021-08-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram2', '0016_auto_20210813_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.CharField(choices=[('like', 'liked'), ('comment', 'commented'), ('follow', 'following')], default='like', max_length=20),
        ),
    ]
